# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/decontamination',
                'doc_host': 'https://CarperAI.github.io',
                'git_url': 'https://github.com/CarperAI/decontamination',
                'lib_path': 'decontamination'},
  'syms': {'decontamination.core': {'decontamination.core.foo': ('core.html#foo', 'decontamination/core.py')}}}
